### ISSUE TITLE
Entries are case-sensitive?

### ISSUE THREAD

**Issue by Aixile** [facebookresearch/MetaCLIP#6]
I notice in `metadata.json`, some words are in lower-case but some words are capitalized
e.g. both `Gas` and `gas` are there
however for some other words, e.g.  `flame` is in the file, `Flame` isn't.
I feel like it might bring some biases, is it intentional or not?

**Comment by howardhsu** [comment]
thx for bring this out, we have similar intuition then conduct an experiment. Check A.6.2 in the paper for explanation.
This is intentional but the current metadata is not optimal for this intention.

Cased words may at risk of introducing low quality writing (then low quality websites -> images), depends on which word should be cased to have higher quality: FLAME > Flame > flame for quality from low to high, think about spam emails...; named entity could be cased for high writing quality.

So far we strictly follow CLIP's description and cased words are introduced by mostly introduced by wikipedia (article name or uni/bigram from starting words of sentences).

**Comment by Aixile** [comment]
Thanks for your detailed explanation!
